# Generated by Django 3.1.1 on 2020-09-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='genero',
            field=models.CharField(choices=[('NÃO INFORMAR', 'Não Informar'), ('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], default='NÃO INFORMAR', max_length=50),
        ),
    ]
